sudo: false
language: node_js
node_js:
- stable
cache:
  yarn: true
  directories:
  - node_modules
branches:
  only:
  - master

# Send coverage data to Coveralls
after_script: "jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage"